name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint (flake8)
        working-directory: backend
        run: |
          pip install flake8
          flake8 --max-line-length=120 || true

      - name: Start backend server
        working-directory: backend
        run: |
          nohup python -m uvicorn main:app --host 127.0.0.1 --port 8000 &
          sleep 3

      - name: Smoke test backend status
        working-directory: backend
        run: |
          python -c "import requests, sys; r = requests.get('http://127.0.0.1:8000/api/status', timeout=5); print('status', r.status_code, r.text); sys.exit(0) if r.status_code==200 else sys.exit(1)"

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend deps
        working-directory: frontend
        run: |
          npm ci

      - name: Build frontend
        working-directory: frontend
        run: |
          npm run build --if-present

