name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 0' # weekly heavy run (Sunday at 02:00 UTC)
  workflow_dispatch:
    inputs:
      heavy-deps:
        description: 'Install heavy ML dependencies (torch, transformers, deepface)'
        required: false
        default: 'false'

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install backend core dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-core.txt
          pip install -r requirements-dev.txt

      - name: Optionally install heavy ML dependencies
        if: ${{ github.event_name == 'schedule' || github.event.inputs.heavy-deps == 'true' }}
        working-directory: backend
        run: |
          pip install -r requirements.txt

      - name: Lint (flake8)
        working-directory: backend
        run: |
          pip install flake8
          flake8 --max-line-length=120 || true

      - name: Start backend server (mock detector)
        working-directory: backend
        run: |
          # Start backend with mock detector for fast tests
          nohup env USE_MOCK_DETECTOR=1 python -m uvicorn main:app --host 127.0.0.1 --port 8000 &
          # wait for server to be ready with retries
          for i in 1 2 3 4 5; do
            sleep 2
            if python -c "import requests,sys;r=requests.get('http://127.0.0.1:8000/api/status',timeout=2); sys.exit(0) if r.status_code==200 else sys.exit(1)" >/dev/null 2>&1; then
              echo 'backend ready'
              break
            else
              echo 'waiting for backend...'
            fi
          done

      - name: Run backend tests (pytest)
        working-directory: backend
        run: |
          pip install pytest
          pytest -q

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend deps
        working-directory: frontend
        run: |
          npm ci

      - name: Build frontend
        working-directory: frontend
        run: |
          npm run build --if-present

